apiVersion: skaffold/v2beta8
kind: Config
metadata:
    name: service-hodappba
build:
    artifacts:
        - image: docker.informatik.hs-furtwangen.de/cnc-hodappba/cnc-webservice
deploy:
    helm:
        releases:
            - name: service-hodappba
              chartPath: charts/service
              artifactOverrides:
                  image: docker.informatik.hs-furtwangen.de/cnc-hodappba/cnc-webservice
