apiVersion: v1
name: service-hodappba
version: 0.1.0
appVersion: "latest"
description: Helm Chart for a basic node.js api service
dependencies:
  - name: mongodb
    version: ^10
    repository: https://charts.bitnami.com/bitnami