apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: servicemonitor-hodappba
    labels:
        app: service
        author: hodappba
spec:
    endpoints:
        - interval: 30s
          path: /hodappba/metrics
          port: web
    selector:
        matchLabels:
            app: service
            author: hodappba
