apiVersion: v1
kind: Service
metadata:
    name: service-{{ .Values.author }}
    labels:
        app: service
        author: {{ .Values.author }}
spec:
    selector:
        app: service
        author: {{ .Values.author }}
    ports:
        - name: web
          port: {{ .Values.web_port }}
          targetPort: 443
