apiVersion: apps/v1
kind: Deployment
metadata:
    name: service-{{ .Values.author }}
    labels:
        app: service
        author: {{ .Values.author }}
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: service
            author: {{ .Values.author }}
    template:
        metadata:
            labels:
                app: service
                author: {{ .Values.author }}
        spec:
            containers:
                - name: api-service
                  image: {{ .Values.image }}
                  env:
                      - name: MONGODB_HOST
                        value: mongodb://service-{{ .Values.author }}-mongodb
                      - name: BACKEND_HOST
                        value: http://localhost:{{ .Values.remote_port }}/hodappba
                      - name: RABBITMQ_HOST
                        value: rabbitmq.rabbitmq  
                  resources:
                      requests:
                          memory: "32Mi"
                      limits:
                          memory: "256Mi"
                  readinessProbe:
                      httpGet:
                          path: "/hodappba/_health/readiness"
                          port: {{ .Values.remote_port }}
                  livenessProbe:
                      httpGet:
                          path: "/hodappba/_health/liveness"
                          port: {{ .Values.remote_port }}
