apiVersion: apps/v1
kind: Deployment
metadata:
    name: service-{{ .Values.author }}
    labels:
        app: service
        author: {{ .Values.author }}
spec:
    replicas: 3
    selector:
        matchLabels:
            app: service
            author: {{ .Values.author }}
    template:
        metadata:
            labels:
                app: service
                author: {{ .Values.author }}
        spec:
            containers:
                - name: api-service
                  image: {{ .Values.image }}:{{ .Chart.AppVersion }}
                  resources:
                      requests:
                          memory: "32Mi"
                      limits:
                          memory: "256Mi"
                  readinessProbe:
                      httpGet:
                          path: "/hodappba/_health/readiness"
                          port: 443
                  livenessProbe:
                      httpGet:
                          path: "/hodappba/_health/liveness"
                          port: 443
